import typer
from pathlib import Path
import molpot
import json
from typing_extensions import Annotated


def inspect_app_script(script_path: Path):
    apps = {}
    try:
        import importlib

        spec = importlib.util.spec_from_file_location(script_path.name, script_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        import inspect

        for class_name, app in inspect.getmembers(module):
            if (
                inspect.isclass(app)
                and issubclass(app, molpot.app.MolpotApp)
                and app.__name__ != "MolpotApp"
            ):
                apps[class_name] = app

    except Exception as e:
        typer.echo(f"Failed to import the script: {e}", err=True)

    return apps


main_cli = typer.Typer()


@main_cli.callback(invoke_without_command=True)
def default_welcome(ctx: typer.Context):
    version = "0.1.0"
    if ctx.invoked_subcommand is None:
        typer.echo(
            r"""
                    __            __ 
   ____ ___  ____  / /___  ____  / /_
  / __ `__ \/ __ \/ / __ \/ __ \/ __/
 / / / / / / /_/ / / /_/ / /_/ / /_  
/_/ /_/ /_/\____/_/ .___/\____/\__/  
                 /_/                 
"""
        )  # generator: https://patorjk.com/software/taag/#p=display&f=Slant&t=molpot
        typer.echo(f"Welcome to MolPot {version}")
        typer.echo()
        typer.echo(ctx.get_help())


config_cli = typer.Typer()
app_cli = typer.Typer()


CONFIG_PATH = Path.home() / ".molcrafts.config"
APP_PATH = Path.home() / ".molpot_app"


def load_config():
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH, "r") as f:
            return json.load(f)


def save_config(config: dict):
    with open(CONFIG_PATH, "w") as f:
        json.dump(config, f)


@config_cli.command(name="set")
def config_set(key: str, value: str):
    config = load_config() or {}
    config[key] = value
    save_config(config)
    typer.echo(f"Set {key} to {value}")


@config_cli.command(name="get")
def config_get(key: str):
    config = load_config()
    if config is None:
        typer.echo("No config found")
    else:
        typer.echo(config.get(key))


def reset_app(dest_path: Path):
    if not dest_path.exists():
        dest_path.mkdir()
        with open(dest_path / "__init__.py", "w") as f:
            f.write(f"# This file is generated by molpot")
    if not (dest_path / "app.json").exists():
        with open(dest_path / "app.json", "w") as f:
            f.write("{}")
    return dest_path


def preload_app():

    app_dir = reset_app(Path.home() / ".molpot_app")
    all_apps = {}
    if not app_dir.exists() and not (app_dir / "app.json").exists():
        return all_apps

    for app_script in app_dir.iterdir():
        if app_script.suffix != ".py" or app_script.name == "__init__.py":
            continue
        apps = inspect_app_script(app_script)
        all_apps.update(apps)
    assert len(set([app.name for app in all_apps.values()])) == len(
        all_apps
    ), "App name should be unique"
    # print(set([app.name for app in all_apps.values()]))
    for app in all_apps.values():

        cli = app.cli

        @cli.callback(invoke_without_command=True)
        def _init_app(config_file: Path):
            return app.load_config(config_file)

        main_cli.add_typer(cli, name=app.name)

    return all_apps


@app_cli.command()
def install(
    script_path: Path,
    editable: Annotated[bool, typer.Option("--editable", "-e")] = False,
):
    """Install a script to the molpot app directory"""

    app_dir = reset_app(Path.home() / ".molpot_app")

    if editable:
        (app_dir / script_path.name).symlink_to(script_path.absolute())
    else:
        import shutil

        shutil.copy(script_path, app_dir / script_path.name)

    app = inspect_app_script(script_path)
    import json

    with open(app_dir / "app.json", "r") as f:
        app_meta = json.load(f)

    for class_name, app in app.items():
        app_meta[f"{script_path}::{class_name}"] = {
            "name": app.name,
            "version": app.version,
        }

    with open(app_dir / "app.json", "w") as f:
        json.dump(app_meta, f)


main_cli.add_typer(config_cli, name="config")
main_cli.add_typer(app_cli, name="app")


def init():
    """initialize everytime call molpot from cli"""
    preload_app()
    ...


init()
