import torch
import torch.nn as nn
import torch.nn.functional as F
from .block import build_mlp
from typing import Callable, Literal
from molpot import NameSpace, alias

class FFLayer(nn.Module):
    r"""`FFLayer` is a shortcut to create a multi-layer perceptron (MLP) or a
    feed-forward network. A `FFLayer` takes one tensor as input of arbitratry
    shape, and parse it to a list of `tf.keras.layers.Dense` layers, specified
    by `n_nodes`. Each dense layer transforms the input variable as:

    $$
    \begin{aligned}
    \mathbb{X}'_{\ldots{}\beta} &= \mathrm{Dense}(\mathbb{X}_{\ldots{}\alpha}) \\
      &= h\left( \sum_\alpha W_{\alpha\beta} \mathbb{X}_{\ldots{}\alpha} + b_{\beta} \right)
    \end{aligned}
    $$

    , where $W_{\alpha\beta}$, $b_{\beta}$ are the learnable weights and biases,
    $h$ is the activation function, and $\mathbb{X}$ can be
    $\mathbb{P}_{i\alpha}$ or $\mathbb{I}_{ij\alpha}$ with $\alpha,\beta$ being
    the indices of input/output channels. The keyward arguments are parsed into
    the class, which can be used to specify the bias, activation function, etc
    for the dense layer. `FFLayer` outputs a tensor with the shape `[...,
    n_nodes[-1]]`.

    In the PiNet architecture, `PPLayer` and `IILayer` are both instances of the
    `FFLayer` class , namely:

    $$
    \begin{aligned}
      \mathbb{I}_{ij\gamma} &= \mathrm{IILayer}(\mathbb{I}'_{ij\beta}) = \mathrm{FFLayer}(\mathbb{I}'_{ij\beta}) \\
      \mathbb{P}_{i\delta} &= \mathrm{PPLayer}(\mathbb{P}''_{i\gamma}) = \mathrm{FFLayer}(\mathbb{P}'_{i\gamma})
    \end{aligned}
    $$

    , with the difference that `IILayer`s have their baises set to zero to avoid
    discontinuity in the model output.
    """

    def __init__(self, *n_nodes: int, activation: Callable | None = F.tanh):
        super().__init__()
        self.mlp = build_mlp(*n_nodes, activation=activation)

    def forward(self, x):
        return self.mlp(x)


class PILayer(nn.Module):
    r"""`PILayer` takes the properties ($\mathbb{P}_{i\alpha},
    \mathbb{P}_{j\alpha}$) of a pair of atoms as input and outputs a set of
    interactions for each pair. The inputs will be broadcasted and concatenated
    as the input of a feed-forward neural network (`FFLayer`), and the
    interactions are generated by taking the output of the `FFLayer` as weights
    of radial basis functions, i.e.:

    $$
    \begin{aligned}
    w_{ij(b\beta)} &= \mathrm{FFLayer}\left((\mathbf{1}_{j}\mathbb{P}_{i\alpha})\Vert(\mathbf{1}_{i}\mathbb{P}_{j\alpha})\right) \\
    \mathbb{I}'_{ij\beta} &= \sum_b W_{ij(b\beta)} \, e_{ijb}
    \end{aligned}
    $$

    , where $w_{ij(b\beta)}$ is an intemediate weight tensor for the
    radial basis functions, output by the `FFLayer`; the output channel is
    reshaped into two dimensions, where $b$ is the index for the basis function
    and $d$ is the index for output interaction.


    `n_nodes` specifies the number of nodes in the `FFLayer`. Note that the last
    element of n_nodes specifies the number of output channels after applying
    the basis function ($d$ instead of $bd$), i.e. the output dimension of
    FFLayer is `[n_pairs,n_nodes[-1]*n_basis]`, the output is then summed with
    the basis to form the output interaction.

    """

    def __init__(self, *n_nodes: int, activation: Callable | None = F.tanh):
        super().__init__()
        self.mlp = build_mlp(*n_nodes, activation=activation)

    def forward(self, p1, pair_i, pair_j, basis):

        p1_i = p1[pair_i]
        p1_j = p1[pair_j]

        inter = p1_i + p1_j
        inter = self.mlp(inter)
        inter = torch.einsum(
            "icb, ib->ic", inter.reshape(-1, p1_i.shape[-1], basis.shape[-1]), basis
        )  # icb := (n_pairs, n_channels, n_basis)
        return inter  # (n_pairs, n_channels)


class IPLayer(nn.Module):
    r"""The IPLayer transforms pairwise interactions to atomic properties

    The IPLayer has no learnable variables and simply sums up the pairwise
    interations. Thus the returned property has the same shape with the
    input interaction, i.e.:

    $$
    \begin{aligned}
    \mathbb{P}_{i\gamma} = \mathrm{IPLayer}(\mathbb{I}_{ij\gamma}) = \sum_{j} \mathbb{I}_{ij\gamma}
    \end{aligned}
    $$

    """

    def forward(self, i1, pair_i, p1):
        return torch.index_add(
            torch.zeros_like(p1, dtype=p1.dtype, device=p1.device),
            0,
            pair_i,
            i1
        )


class InvarLayer(nn.Module):

    def __init__(
        self,
        pp_nodes: list[int],
        pi_nodes: list[int],
        ii_nodes: list[int],
        activation: Callable = F.tanh,
    ):
        super().__init__()
        self.pp_layer = FFLayer(*pp_nodes, activation=activation)
        self.pi_layer = PILayer(*pi_nodes, activation=activation)
        self.ii_layer = FFLayer(*ii_nodes, activation=activation)
        self.ip_layer = IPLayer()

    def forward(self, pair_i, pair_j, p1, basis):
        i1 = self.pi_layer(p1, pair_i, pair_j, basis)
        i1 = self.ii_layer(i1)
        p1 = self.ip_layer(i1, pair_i, p1)
        p1 = self.pp_layer(p1)

        return p1, i1


class PIXLayer(nn.Module):
    r"""`PIXLayer` takes the equalvariant properties ${}^{3}\mathbb{P}_{ix\zeta}$ as input and outputs interactions for each pair ${}^{3}\mathbb{I}_{ijx\zeta}$. The `PIXLayer` has two styles, specified by the `weighted` argument:

    `weighted`:

    $$
    \begin{aligned}
    {}^{3}\mathbb{I}_{ijx\gamma} = W_{\zeta\gamma}^{'} \mathbf{1}_{j}^{'} {}^{3}\mathbb{P}_{ix\zeta} + W_{\zeta\gamma}^{''} \mathbf{1}_{i}^{''} {}^{3}\mathbb{P}_{jx\zeta}
    \end{aligned}
    $$

    `non-weighted`:

    $$
    \begin{aligned}
    {}^{3}\mathbb{I}_{ijx\zeta} = \mathbf{1}_{j} {}^{3}\mathbb{P}_{ix\zeta}
    \end{aligned}
    $$

    """

    def __init__(
        self,
        *n_nodes: int,
        activation: Callable | None = F.tanh,
    ):
        super().__init__()
        self.wi = build_mlp(*n_nodes, activation=activation, last_bias=False)
        self.wj = build_mlp(*n_nodes, activation=activation, last_bias=False)

    def forward(self, prop, pair_i, pair_j):

        prop_i = prop[pair_i]
        prop_j = prop[pair_j]

        return self.wi(prop_i) + self.wj(prop_j)


class ScaleLayer(nn.Module):

    def forward(self, px, p1):
        return px * p1  # 'pcf,p...f->pcf'


class SelfDotLayer(nn.Module):

    def forward(self, p):
        return torch.einsum("ixr, ixr->ir", p, p)[:, None, :]


class EqvarLayer(nn.Module):

    def __init__(self, n_nodes: list[int]):
        super().__init__()
        self.pp_layer = FFLayer(*n_nodes, activation=None)
        self.pi_layer = PIXLayer(*n_nodes, activation=None)
        self.ii_layer = FFLayer(*n_nodes, activation=None)
        self.ip_layer = IPLayer()

        self.scale_layer = ScaleLayer()

    def forward(self, pair_i, pair_j, px, diff, i1):

        ix = self.pi_layer(px, pair_i, pair_j)
        ix = self.scale_layer(ix, i1)
        scaled_diff = self.scale_layer(diff[:, :, None], i1)
        ix = ix + scaled_diff
        px = self.ip_layer(ix, pair_i, px)
        px = self.pp_layer(px)
        ix = self.ii_layer(ix)

        return px, ix


class GCBlock(nn.Module):

    def __init__(
        self,
        rank: Literal[1, 3],
        pp_nodes: list[int],
        pi_nodes: list[int],
        ii_nodes: list[int],
        activation: Callable | None = F.tanh,
    ):
        super().__init__()
        self.rank = rank
        self.p1_layer = InvarLayer(pp_nodes, pi_nodes, ii_nodes, activation)
        # self.p3_layer = EqvarLayer([pp_nodes[0], pp_nodes[-1]])

        # self.scale_layer = ScaleLayer()
        # self.dot_layer = SelfDotLayer()

    def forward(self, p1, atom_batch, pair_i, pair_j, pair_batch, basis) -> dict[str, torch.Tensor]:
        p1, i1 = self.p1_layer(pair_i, pair_j, p1, basis)
        # prop_list = [p1]
        # n_prop_list = [1]
        # if self.rank >= 3:
        #     p3 = inputs["pinet", "p3"]
        #     diff_p3 = inputs["pairs", "norm_diff"]
        #     p3, i3 = self.p3_layer(pair_i, pair_j, p3, diff_p3, i1)
        #     inputs["pinet", "i3"] = i3
        #     prop_list.append(p3)
        #     n_prop_list.append(3)

        # prop_list = torch.concat(prop_list, dim=1)
        # prop_list = torch.split(prop_list, n_prop_list, dim=1)
        # inputs["pinet", "p1"] = prop_list[0]
        # if self.rank >= 3:
        #     p3t1 = self.scale_layer(p3, prop_list[1])
        #     inputs["pinet", "p3"] = p3t1

        return p1, i1


class ResUpdate(nn.Module):

    def __init__(self):
        super().__init__()

    def forward(self, old, new):
        return old + new


class PiNet(nn.Module):

    in_keys = [alias.Z, alias.pair_diff, alias.pair_i, alias.pair_j]
    out_keys = [("pinet", "p1"), ("pinet", "i1")]

    def __init__(
        self,
        depth: int,
        basis_fn: Callable | None = None,
        cutoff_fn: Callable | None = None,
        pp_nodes: list[int] = [16, 16],
        pi_nodes: list[int] = [16, 16],
        ii_nodes: list[int] = [16, 16],
        activation: Callable | None = F.tanh,
        max_atomtypes: int = 100,
        rank: Literal[1, 3] = 3,
    ):
        super().__init__()
        self.rank = rank
        pp_nodes = pp_nodes.copy()
        pi_nodes = pi_nodes.copy()
        ii_nodes = ii_nodes.copy()
        self.labels = NameSpace("pinet")
        self.labels.set(
            "p1",
            "scalar property",
            float,
            shape=(None, 1, ii_nodes[-1]),
        )
        if self.rank >= 3:
            self.labels.set(
                "p3",
                "vectorial property",
                float,
                shape=(None, 3, ii_nodes[-1]),
            )

        self.depth = depth
        self.basis_fn = basis_fn
        self.cutoff_fn = cutoff_fn
        self.n_basis = self.basis_fn.n_rbf

        self.embedding = nn.Embedding(max_atomtypes, self.n_basis, padding_idx=0)

        pi_nodes[-1] *= self.n_basis
        self.before_gc_block_layer = nn.Linear(self.n_basis, pp_nodes[0])

        self.gc_blocks = nn.ModuleList(
            [
                GCBlock(self.rank, pp_nodes, pi_nodes, ii_nodes, activation)
                for _ in range(depth)
            ]
        )

        self.res_update = ResUpdate()

    def forward(self, Z, atom_mask, pair_dist, pair_diff, pair_i, pair_j, pair_mask) -> None:

        pair_dist = torch.norm(pair_diff, dim=-1)
        pair_i = pair_i.to(torch.int64) # for scatter
        pair_j = pair_j.to(torch.int64) 
        norm_pair_diff = pair_diff / pair_dist[..., None]

        basis = self.basis_fn(pair_dist)
        fc = self.cutoff_fn(pair_dist)

        basis = basis * fc[..., None]
        p1 = self.embedding(Z)

        # (n_atoms, ) -> (n_atoms, n_basis)
        p1 = self.before_gc_block_layer(p1)  
        # if self.rank >= 3:
        #     p3 = torch.zeros([n_atoms, 3, p1.shape[-1]], device=p1.device)
            # inputs["pinet", "p3"] = p3

        # inputs["pinet", "p1"] = p1
        
        for i in range(self.depth):
            new_p1, i1 = self.gc_blocks[i](p1, atom_mask, pair_i, pair_j, pair_mask, basis)
            p1 = self.res_update(new_p1, p1)
            # if self.rank >= 3:
            #     inputs["pinet", "p3"] = self.res_update(inputs["pinet", "p3"], p3)
            #     p3 = inputs["pinet", "p3"]
        return {
            ("pinet", "p1"): p1,
            ("pinet", "i1"): i1
        }
