
import torch
import torch.nn as nn
from molpot import Frame, alias
from .handler import MDHandler
from .main import MDMainEvents

class Integrator(MDHandler):
    """
    Basic integrator class template. Uses the typical scheme of propagating
    frame momenta in two half steps and frame positions in one main step.
    The half steps are defined by default and only the _main_step function
    needs to be specified. Uses atomic time units internally.

    If required, the torch graphs generated by this routine can be detached
    every step via the detach flag.

    Args:
        time_step (float): Integration time step in femto seconds.
    """

    def __init__(self, time_step: float):
        super(Integrator, self).__init__(
            {MDMainEvents.INITIAL_INTEGRATE, MDMainEvents.FINAL_INTEGRATE}, (0, 0)
        )
        # Convert fs to internal time units.
        self.time_step = time_step

    def half_step(self, frame: Frame):
        raise NotImplementedError

    def main_step(self, frame: Frame):
        raise NotImplementedError


class VelocityVerlet(Integrator):
    """
    Standard velocity Verlet integrator for non ring-polymer simulations.

    Args:
        time_step (float): Integration time step in femto seconds.
    """

    def __init__(self, time_step: float):
        super(VelocityVerlet, self).__init__(time_step)

    def half_step(self, frame: Frame):
        r"""
        Half steps propagating the frame momenta according to:

        ..math::
            p = p + \frac{1}{2} F \delta t

        Args:
            frame (schnetpack.md.Frame): Frame class containing all molecules and their
                             replicas.
        """
        frame["atoms", "momenta"] = frame["atoms", "momenta"] + 0.5 * frame["atoms", "forces"] * self.time_step

    def main_step(self, frame: Frame):
        r"""
        Propagate the positions of the frame according to:

        ..math::
            q = q + \frac{p}{m} \delta t

        Args:
            frame (schnetpack.md.Frame): Frame class containing all molecules and their
                             replicas.
        """
        frame[alias.R] = (
            frame[alias.R] + self.time_step * frame["atoms", "momenta"] / frame["atoms", "masses"]
        )
