name: build_dev_image
on:
  push:
    branches:
      - dev
      - master

jobs:
  build-cpu:

    permissions:
        packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/cpu/devcontainer.json
          imageName: ghcr.io/molcrafts/molpot
          imageTag: latest-cpu

  build-gpu:

    permissions:
        packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/gpu/devcontainer.json
          imageName: ghcr.io/molcrafts/molpot
          imageTag: latest-gpu
